BOARD_WIDTH, BOARD_HEIGHT = BOARD_SIZE = (10, 10)
CELL_WIDTH, CELL_HEIGHT = CELL_SIZE=(32, 32)

SCREEN_WIDTH, SCREEN_HEIGHT = WINDOW_SIZE = (BOARD_WIDTH * CELL_WIDTH, BOARD_HEIGHT * CELL_HEIGHT)
WINDOW_CAPTION = "Engine"
SCALE = 4
