import numpy as np

SHOW_FPS = True

SCALE = 4
SCALE = np.array((SCALE,))

BOARD_WIDTH, BOARD_HEIGHT = BOARD_SIZE = (10, 10)
CELL_WIDTH, CELL_HEIGHT = CELL_SIZE= (16, 16) * SCALE

SCREEN_WIDTH, SCREEN_HEIGHT = WINDOW_SIZE = (BOARD_WIDTH * CELL_WIDTH, BOARD_HEIGHT * CELL_HEIGHT)
WINDOW_CAPTION = "Turn Based"
